version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    command: sh -c "((sleep 10 && kafka-topics.sh --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 2 --topic delivery) &)&& /opt/bitnami/scripts/kafka/entrypoint.sh /run.sh"

  postgres:
    image: 'postgres'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=tarea2
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  producer:
    container_name: producer
    build: ./producer
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - zookeeper

  consumer:
    container_name: consumer
    build: ./consumer
    ports:
      - "3001:3001"
    depends_on:
      - kafka
      - producer